require 'cucumber/rake/task'

task :default => :run

Cucumber::Rake::Task.new :run do |t|
  t.cucumber_opts = '--format pretty --tags "not @wip"'
end

Cucumber::Rake::Task.new :wip do |t|
  t.cucumber_opts = '--format pretty --tags "@wip"'
end
