desc 'Run unit tests for lib/ directory objects'
task :default => :test

# common lib directory
#
lib_dir = File.join __dir__, 'lib'
lib_dir = File.expand_path lib_dir
raise lib_dir unless Dir.exists? lib_dir
$:.<< lib_dir unless $:.include? lib_dir

# tasks are at ./rakelib/*
#
task :idempotent => %i[
  org_to_tests
]
task :org_to_tests => %i[
  org_to_json
  json_to_tests
]

# unit tests
#
require 'rake/testtask'
Rake::TestTask.new do |t|
  t.test_files = FileList['test/**/*_test.rb']
end
